config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create]

  get 'cart/add/:book_id', to: 'cart#add_book', as: 'add_to_cart'
  patch 'cart/update-quantity', to: 'cart#update_quantity', as: 'update_cart_quantity'
  get 'cart/show', to: 'cart#show', as: 'view_cart'

  delete 'logout', to: 'sessions#destroy'
  get 'store/index', as: 'store_index'

  get 'settings', to: 'settings#index'
  get 'orders/address', to: 'orders#address', as: 'add_order_address'
  get 'orders/index', to: 'orders#index', as: 'orders'
  post 'orders/address', to: 'orders#save_address', as: 'save_order_address'
  get 'orders/checkout', to: 'orders#checkout', as: 'orders_checkout'
  get 'orders/:id', to: 'orders#show', as: 'order'
  post 'orders/finish', to: 'orders#finish_checkout', as: 'finish_checkout'
  get '/admin', to: 'admin_session#new'
  post '/admin', to: 'admin_session#create', as: 'admin_session'
  get '/admin/orders', to: 'admin#orders', as: 'admin_orders'
  get '/admin/users', to: 'admin#users', as: 'admin_users'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items

  accepts_nested_attributes_for :line_items

  def add_book(book)
    line_item = line_items.find_by(book_id: book.id)
    if line_item
      line_item.quantity += 1
    else
      line_item = line_items.build(book_id: book.id)
      line_item.price = line_item.book.price
    end
    line_item
  end

  def empty?
    line_items.count.zero?
  end

  def count
    line_items.count
  end

  def total_line_items
    line_items.to_a.sum { |item| item.price * item.quantity }
  end

  alias total total_line_items
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include CartHelper
  before_action :set_cart

  def show
  end

  def update_quantity
    line_items = params.require(:cart).permit(line_items_attributes: [:id, :quantity])
    @cart.update line_items
    @cart.line_items.where(quantity: 0).destroy_all
    redirect_to view_cart_path, notice: 'Quantities updated'
  end

  def add_book
    book = Book.find params[:book_id]
    @line_item = @cart.add_book book
    if @line_item.save
      redirect_to view_cart_path, notice: 'Added book to cart'
    else
      redirect_to book_path(book), alert: 'Error adding book to cart. ' + @line_item.errors.full_messages.to_sentence
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
  def set_cart
    @cart = Cart.find_by_id session[:cart_id]
    return if @cart
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/views/cart/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<% if @cart.empty? %>
  <h3>Your cart is empty.</h3>
<% else%>
  <h3>Your cart contains <%= @cart.count %> items: </h3>
  <div class="col-md-8">

  <%= form_for @cart, url: update_cart_quantity_path do |f| %>
    <table class="table table-striped">
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price</th>
        <th class="text-right">Total</th>
      </tr>
      <% @cart.line_items.each_with_index do |item, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= item.book.name %></td>
          <td>
            <%= f.fields_for :line_items, item do |item_form| %>
              <%= item_form.hidden_field :id %>
              <%= item_form.number_field :quantity, style: 'width: 35px' %>
            <% end %>
          </td>
          <td><%= item.price %>€</td>
          <td class="text-right"><%= item.quantity * item.price %>€</td>
        </tr>
      <% end %>
      <tr>
        <td colspan="5"></td>
      </tr>
      <tr>
        <td colspan="5" class="text-right">
          <%= f.submit 'Update Cart', class: 'btn btn-default' %>
        </td>
      </tr>
    </table>
  <% end %>
  </div>
  <div class="col-md-4 text-right checkout-side">
    <div>
      <h3>Order Total: <%= @cart.total %>€</h3>
    </div>
    <a href="<%= add_order_address_path %>" class="btn btn-default">Go to Checkout</a>
  </div>
<% end %>