config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create]

  get 'cart/add/:book_id', to: 'cart#add_book', as: 'add_to_cart'
  patch 'cart/update-quantity', to: 'cart#update_quantity', as: 'update_cart_quantity'
  get 'cart/show', to: 'cart#show', as: 'view_cart'

  delete 'logout', to: 'sessions#destroy'
  get 'store/index', as: 'store_index'

  get 'settings', to: 'settings#index'
  get 'orders/address', to: 'orders#address', as: 'add_order_address'
  get 'orders/index', to: 'orders#index', as: 'orders'
  post 'orders/address', to: 'orders#save_address', as: 'save_order_address'
  get 'orders/checkout', to: 'orders#checkout', as: 'orders_checkout'
  get 'orders/:id', to: 'orders#show', as: 'order'
  post 'orders/finish', to: 'orders#finish_checkout', as: 'finish_checkout'
  get '/admin', to: 'admin_session#new'
  post '/admin', to: 'admin_session#create', as: 'admin_session'
  get '/admin/orders', to: 'admin#orders', as: 'admin_orders'
  get '/admin/users', to: 'admin#users', as: 'admin_users'
end

app/controllers/admin_session_controller.rb
class AdminSessionController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by(username: admin_params[:username].downcase)
    if admin
      if admin.authenticate(admin_params[:password])
        log_in_admin admin
        return redirect_to store_index_path, notice: 'Successfully logged in'
      end
    end
    flash[:danger] = 'Invalid username/password combination'
    render 'new'
  end

  def destroy
    session.delete :user_id
    redirect_to store_index_path, notice: 'Successfully logged out'
  end

  def admin_params
    params.require(:admin).permit(:username, :password)
  end
end

app/views/admin_session/new.html.erb
<div class="col-md-5">
  <h2>Login</h2>
  <% if flash[:danger] %>
  <p class="alert alert-danger"><%= flash[:danger] %></p>
  <% end %>
  <%= form_for(:admin, url: admin_session_path) do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

    </div>
    <div class="form-group">
      <%= f.submit "Log in", class: "btn btn-default" %>
    </div>
  <% end %>
</div>