config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create]

  get 'cart/add/:book_id', to: 'cart#add_book', as: 'add_to_cart'
  patch 'cart/update-quantity', to: 'cart#update_quantity', as: 'update_cart_quantity'
  get 'cart/show', to: 'cart#show', as: 'view_cart'

  delete 'logout', to: 'sessions#destroy'
  get 'store/index', as: 'store_index'

  get 'settings', to: 'settings#index'
  get 'orders/address', to: 'orders#address', as: 'add_order_address'
  get 'orders/index', to: 'orders#index', as: 'orders'
  post 'orders/address', to: 'orders#save_address', as: 'save_order_address'
  get 'orders/checkout', to: 'orders#checkout', as: 'orders_checkout'
  get 'orders/:id', to: 'orders#show', as: 'order'
  post 'orders/finish', to: 'orders#finish_checkout', as: 'finish_checkout'
  get '/admin', to: 'admin_session#new'
  post '/admin', to: 'admin_session#create', as: 'admin_session'
  get '/admin/orders', to: 'admin#orders', as: 'admin_orders'
  get '/admin/users', to: 'admin#users', as: 'admin_users'
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items
  belongs_to :country
  belongs_to :user, optional: true

  enum payment_type: {
    'Credit card' => 0,
    'Pay on delivery' => 1
  }
  enum status: {
    unconfirmed: 0,
    confirmed: 1
  }
  validates :name, :address, :country_id, :payment_type, presence: true
  validates :payment_type, inclusion: payment_types.keys

  AMOUNT_FOR_FREE_SHIPPING = 400

  def add_cart_contents(cart)
    cart.line_items.each do |item|
      #item.cart_id = nil
      line_items << item
    end
  end

  def update_book_sold_count
    line_items.each do |line_item|
      book = line_item.book
      book.update_attribute(:sold_count, book.sold_count + line_item.quantity)
    end
  end

  def total
    @total ||= line_items.to_a.sum { |item| item.price * item.quantity }
  end

  def item_count
    line_items.map(&:quantity).sum
  end

  def total_with_tax
    total + tax
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include CartHelper
  before_action :check_cart, except: [:index, :show]
  before_action :check_login
  before_action :find_existing_order, only: [:checkout, :finish_checkout]

  def index
    @orders = Order.confirmed.where(user_id: @current_user.id)
  end

  def show
    id = params[:id]
    @order = Order.confirmed.where(user_id: @current_user.id).where(id: id).first
    unless @order
      redirect_to orders_path, alert: 'Order not found'
      return
    end
  end

  def address
    order.name ||= current_user.name
    @countries = Country.all
  end

  def save_address
    order_params = params.require(:order).permit(:name, :address, :country_id, :payment_type)
    order.assign_attributes(order_params)
    unless @order.save
      redirect_to add_order_address_path, alert: "Error saving order. #{@order.errors.full_messages.join(', ')}"
      return
    end
    @order.add_cart_contents(@cart)
    session[:order_id] = @order.id
    redirect_to orders_checkout_path
  end

  def checkout
    unless @order
      redirect_to store_index_path, error: 'Order error'
      return
    end
    @order.tax = @order.total * @order.country.tax / 100.0
    @order.shipping_cost = @order.total_with_tax > Order::AMOUNT_FOR_FREE_SHIPPING ? 0 : 10
    @order.save
  end

  def finish_checkout
    @order.confirmed!
    @order.update_attribute(:user_id, @current_user.id)
    @order.update_book_sold_count
    OrderMailer.new_order(@order).deliver_now
    OrderMailer.new_customer_order(@order).deliver_now
    session.delete :order_id
    session.delete :cart_id
    redirect_to root_path, notice: 'Order sent successfully'
  end

  private

  def order
    find_existing_order
    @order ||= Order.new
    @order
  end

  def find_existing_order
    @order = Order.find_by_id session[:order_id]
  end

  def check_cart
    set_cart
    if @cart.nil? || @cart.empty?
      redirect_to store_index_path, notice: 'Cart empty'
      return
    end
  end

  def check_login
    return true if logged_in?
    redirect_to new_session_path, notice: 'Log in to continue'
  end
end

app/views/orders/address.html.erb
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<div class="col-md-6 col-sm-6">
  <%= form_for @order, url: save_order_address_path, method: :post do |f| %>
  <fieldset>
    <legend>Address</legend>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :country_id %>
      <%= f.collection_select(:country_id, @countries, :id, :name, { prompt: true }, { class: 'form-control' }) %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Payment method</legend>
    <div class="form-group">
      <%= f.label :payment_type %>
      <%= f.select :payment_type, Order.payment_types.keys, { prompt: true }, { class: 'form-control' } %>
    </div>
  </fieldset>
  <div class="form-group">
    <%= f.submit 'Continue', class: 'btn btn-default' %>
  </div>
  <% end %>
</div>
<div class="col-md-4 col-sm-4 col-md-offset-2 col-sm-offset-2">
  <h4>Order Summary</h4>
  <table class="table">
    <% @cart.line_items.each_with_index do |item, index| %>
      <tr class="info">
        <td>
          <%= link_to(item.book.name, book_path(item.book)) %>
        </td>
        <td>
          x
        </td>
        <td>
          <%= item.quantity %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/orders/checkout.html.erb
<h3>Finish your order</h3>

<div class="col-sm-9 col-md-9">
  <table class="table">
    <tr>
      <td>
        Total
      </td>
      <td>
        <%= number_to_currency(@order.total, unit: '€', precision: 2) %>
      </td>
    </tr>
    <tr>
      <td>Tax for <%= @order.country.name %></td>
      <td><%= number_to_currency(@order.tax, unit: '€', precision: 2) %></td>
    </tr>
    <tr>
      <td>Shipping cost</td>
      <td><%= number_to_currency(@order.shipping_cost, unit: '€', precision: 2) %></td>
    </tr>
    <tr>
      <td>Grand Total</td>
      <td><%= number_to_currency(@order.total_with_tax + @order.shipping_cost, unit: '€', precision: 2) %></td>
    </tr>
    <tr>
      <td colspan="2">
        <%= link_to 'Finish order', finish_checkout_path, method: :post, class: 'btn btn-success' %>
      </td>
    </tr>
  </table>
</div>

<div class="col-sm-3 col-md-3">
  <% if @order.shipping_cost > 0 %>
    <p class="alert alert-warning text-center">
    Add <%= number_to_currency(Order::AMOUNT_FOR_FREE_SHIPPING - @order.total_with_tax, unit: '€', precision: 2) %> more for free shipping
    </p>
  <% end %>
</div>

app/views/orders/index.html.erb
<% if @orders.empty? %>
  You don't have any previous orders
<% else %>
  <table class="table table-bordered">
    <tr>
      <th>Order id</th>
      <th>Order date</th>
      <th>Number of items</th>
      <th>Total</th>
      <th>Action</th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %>
        <td>
          <%= order.created_at %>
        </td>
        <td><%= order.item_count %></td>
        <td><%= number_to_currency(order.total_with_tax + order.shipping_cost, unit: '€', precision: 2) %></td>
        <td><%= link_to('View details', order_path(order)) %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/orders/show.html.erb
<h3>Order details</h3>
<h4>Items in the order:</h4>

<table class="table table-bordered">
  <tr>
    <th>Book title</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <% @order.line_items.each do |item| %>
    <tr>
      <td><%= link_to(item.book.name, book_path(item.book.id)) %></td>
    <td><%= item.quantity %></td>
    <td><%= number_to_currency(item.price, unit: '€', precision: 2) %></td>
    </tr>
  <% end %>
</table>

<h4>Items in the order:</h4>
<table class="table-bordered table">
  <tr>
    <td>Shipping cost</td>
    <td><%= number_to_currency(@order.shipping_cost, unit: '€', precision: 2) %><br></td>
  </tr>
  <tr>
    <td>Payed with</td>
    <td><%= @order.payment_type %></td>
  </tr>
  <tr>
    <td>Tax</td>
    <td><%= number_to_currency(@order.tax, unit: '€', precision: 2) %></td>
  </tr>
</table>
<br><br><br>
<%= link_to('Back to orders', orders_path) %>