config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :books
  resources :authors
  resources :categories
  resources :users
  resources :sessions, only: [:new, :create]

  get 'cart/add/:book_id', to: 'cart#add_book', as: 'add_to_cart'
  patch 'cart/update-quantity', to: 'cart#update_quantity', as: 'update_cart_quantity'
  get 'cart/show', to: 'cart#show', as: 'view_cart'

  delete 'logout', to: 'sessions#destroy'
  get 'store/index', as: 'store_index'

  get 'settings', to: 'settings#index'
  get 'orders/address', to: 'orders#address', as: 'add_order_address'
  get 'orders/index', to: 'orders#index', as: 'orders'
  post 'orders/address', to: 'orders#save_address', as: 'save_order_address'
  get 'orders/checkout', to: 'orders#checkout', as: 'orders_checkout'
  get 'orders/:id', to: 'orders#show', as: 'order'
  post 'orders/finish', to: 'orders#finish_checkout', as: 'finish_checkout'
  get '/admin', to: 'admin_session#new'
  post '/admin', to: 'admin_session#create', as: 'admin_session'
  get '/admin/orders', to: 'admin#orders', as: 'admin_orders'
  get '/admin/users', to: 'admin#users', as: 'admin_users'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :categories
  include SessionsHelper
  include AdminHelper

  def categories
    @categories = Category.all
  end

  def authenticate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_book_item.html.erb
<ul class="thumbnail-list">
  <% books.each do |book| %>
    <li>
      <a href="<%= book_path(book) %>">
        <%= raw "<img src='data:image/png;base64,#{book.cover}' class=\"book-image\">" %>
      </a>
      <%= link_to(book.name, book, class: 'block book-title', title: book.name) %>
      <%= link_to(book.author.name, book.author, class: 'block') %>
      <div class="book-price"><%= book.price %> €</div>
      <a type="button" class="btn btn-default navbar-btn" href="<%= add_to_cart_path(book) %>">Add to Cart</a>
    </li>
  <% end %>
</ul>

app/views/application/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3">
        <ul class="nav navbar-nav">
          <li>
            <a class="navbar-brand" href="<%= root_url %>">
              <%= image_tag 'logo.png', id: 'logo' %>
              <span>book-a-book</span>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-6 col-sm-6">
        <ul class="nav navbar-nav">
          <li>
            <div class="input-group">
              <input type="hidden" name="search_param" value="all" id="search_param">
              <input type="text" class="form-control" name="x" placeholder="Search">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
              </span>
            </div>
          </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul class="nav navbar-nav pull-right navbar-right">
          <% if logged_in? && !admin_logged_in?%>
            <li><%= link_to 'Cart', view_cart_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Settings", settings_path %></li>
                <li><%= link_to "Orders", orders_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% elsif admin_logged_in? %>
            <li><%= link_to 'Orders', admin_orders_path %></li>
            <li><%= link_to 'Users', admin_users_path %></li>
          <% else %>
            <li><%= link_to "Log in", new_session_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/application/_sidebar.html.erb
<ul class="list-group list-unstyled">
  <% @categories.each do |category| %>
    <li class="">
      <%= link_to(category.name, category_path(category), class: 'no-color list-group-item') %>
    </li>
  <% end %>
</ul>